In [2]:
import numpy as np

In [4]:
dataset = np.genfromtxt('./student_scores.csv',delimiter=',', skip_header=True)
dataset


array([[ 2.5, 21. ],
       [ 5.1, 47. ],
       [ 3.2, 27. ],
       [ 8.5, 75. ],
       [ 3.5, 30. ],
       [ 1.5, 20. ],
       [ 9.2, 88. ],
       [ 5.5, 60. ],
       [ 8.3, 81. ],
       [ 2.7, 25. ],
       [ 7.7, 85. ],
       [ 5.9, 62. ],
       [ 4.5, 41. ],
       [ 3.3, 42. ],
       [ 1.1, 17. ],
       [ 8.9, 95. ],
       [ 2.5, 30. ],
       [ 1.9, 24. ],
       [ 6.1, 67. ],
       [ 7.4, 69. ],
       [ 2.7, 30. ],
       [ 4.8, 54. ],
       [ 3.8, 35. ],
       [ 6.9, 76. ],
       [ 7.8, 86. ]])

In [5]:
dataset[:,1]

array([21., 47., 27., 75., 30., 20., 88., 60., 81., 25., 85., 62., 41.,
       42., 17., 95., 30., 24., 67., 69., 30., 54., 35., 76., 86.])

In [7]:
avg_score = np.mean(dataset[:,1])
print(avg_score)

51.48


In [40]:
hours_studied = dataset[:,0]
print(hours_studied)
test_scores = dataset[:,1]
print(np.mean(hours_studied))
print(np.mean(test_scores))


[2.5 5.1 3.2 8.5 3.5 1.5 9.2 5.5 8.3 2.7 7.7 5.9 4.5 3.3 1.1 8.9 2.5 1.9
 6.1 7.4 2.7 4.8 3.8 6.9 7.8]
5.012
51.48


In [43]:
above_average_studiers = hours_studied > np.mean(hours_studied)
hours_studied[above_average_studiers]

array([5.1, 8.5, 9.2, 5.5, 8.3, 7.7, 5.9, 8.9, 6.1, 7.4, 6.9, 7.8])